version: '2'

services:
  app:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/app
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER:'pg'
      - POSTGRES_PASSWORD:'pg'
      - POSTGRES_DB:'hn'
